# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# FB Login API credentials
FACEBOOK_APP_KEY: '277261499413987' 
FACEBOOK_APP_SECRET: 'b925eaea46855a53e4b7b99f9d968f7e'

# Google client credentials
GOOGLE_CLIENT_ID: '775025959978-ihansu2d4u2br1u0491mf3p0pini8slu.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET: 'DNXq-fPvRDtbpB9NlhnXtMGw'

# Amazon AWS API Keys
aws_access_key: 'AKIAJ2OMBHUHTBGKGU4Q'
aws_access_secret: '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'